### ISSUE TITLE
Filter out and store desired fields + values from fxa-homepage.json (perf-results file)

### ISSUE THREAD

**Issue by stephendonner** [mozilla/wpt-api#5]
Before sending/publishing the results data we care about to S3, etc., services/stores, we need to filter (and strip out) just the data we want, from the only (for now) build-artifact we export/save: fxa-homepage.json

Using ```jq```[0] for starters, we should try filtering out these fields:

https://github.com/mozilla/fxa-webpagetest-driver/blob/fbadc4c268e8180f65225fae9489a83f51994984/queries.js#L12-L29

For the time being, we'll want to write the filtered data to a stats.json (or better-named) file.

I'm assigning this to me and taking, for now, but feel free to help/take!

@soulgalore - thoughts/tips?

[0] https://hub.docker.com/r/realguess/jq/

**Comment by stephendonner** [comment]
```jq '.data.runs."1".firstView.TTFB'``` yields 441 with the now-latest https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt-api.fxa-perf/71/artifact/fxa-homepage.json, so I know that's a valid query.

But I haven't yet gotten it working through Docker, with the 1.4 tag of https://hub.docker.com/r/realguess/jq/

<img width="1666" alt="screen shot 2018-04-24 at 12 16 21 am" src="https://user-images.githubusercontent.com/387249/39172298-2e71d242-4756-11e8-8bd5-457c0d47598d.png">

/cc @philbooth @davehunt

**Comment by stephendonner** [comment]
```docker run -t --rm --name jq realguess/jq:1.4 echo "data.runs.1.firstView.TTFB" $(cat fxa-homepage.json | jq .data.runs."1".firstView.TTFB)
-bash: jq: command not found
data.runs.1.firstView.TTFB
```
I know this'll end up being a silly typo or omission; I'll resume work on this tomorrow, and hopefully have it working.

**Comment by davehunt** [comment]
I didn't try [realguess/jq](https://hub.docker.com/r/realguess/jq/) but this worked for me with [colstrom/jq](https://hub.docker.com/r/colstrom/jq/):

```
$ docker run --mount type=bind,source="${PWD}",target=/data colstrom/jq '.data.runs."1".firstView.TTFB' data/fxa-homepage.json
439
```

**Comment by davehunt** [comment]
Also works with realguess, but you need to explicitly call `jq`:

```
$ docker run --mount type=bind,source="${PWD}",target=/data realguess/jq jq '.data.runs."1".firstView.TTFB' data/fxa-homepage.json
439
```

**Comment by soulgalore** [comment]
At first when we started to use Browsertime (it also produces a JSON so it will be the same with WPT API) we used jq and and piped the result to nc like in this example: https://github.com/sitespeedio/browsertime#send-metrics-to-graphite

That worked fine when we wanted to try it out (we did a project where we tried it with mahimahi and WebPageReplay). 

But then when we started to use it for real, I did a small wrapper in NodeJS that just picked the metrics we want: https://github.com/soulgalore/bttostatsv (statsv is our endpoint that we use to push in the metrics to graphite). Our current setup with Browsertime/WebPageReplay is documented [here](https://wikitech.wikimedia.org/wiki/Performance/WebPageReplay) (that will later be how we test on commits etc). The WebPageTest setup is [here](https://wikitech.wikimedia.org/wiki/WebPageTest) (now updated for Linux). 

Before I would start doing something like this I would iterate a couple of times which metrics you want and how you will use them. For example for WebPageTest we use the lowest value of 5 runs to get stable metrics (instead of taking median). For browsertime we take the median but also store the min so we have it. We also now always take the standard deviation (check the graphs to the right) to make it easier to spot if one of the URLs is problematic: https://grafana.wikimedia.org/dashboard/db/webpagetest

**Comment by stephendonner** [comment]
Leaving open for part two: parsing for, extracting, and writing out selected/desired performance metrics to stats.json, and then archiving it.  We should probably also start thinking about checks and asserts to fail the build in Jenkins if one or both of these data files are missing, too, right @davehunt ?
